#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ciftcidenEve.Droid.Resource", IsApplication=true)]

namespace ciftcidenEve.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int card_icon = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int ciftcidenEve_logo = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int domates = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int facebookIcon = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int homePage_icon = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int icecek_cay_icon = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int icecek_kahve_icon = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int icecek_meyveSuyu_icon = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int icecek_salgam_icon = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int icecek_sut_icon = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int icon_about = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int icon_feed = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int instagramIcon = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int kahvaltilik_bal_icon = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int kahvaltilik_peynir_icon = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int kahvaltilik_recel_icon = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int kahvaltilik_yumurta_icon = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int kahvaltilik_zeytin_icon = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int linkedinIcon = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int mainLogo = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int meyve_avokado_icon = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int meyve_cilek_icon = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int meyve_elma_icon = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int meyve_fidani = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int meyve_mandalina_icon = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int meyve_uzum_icon = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int profil_icon = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int recel = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int sabun = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int satici_icon = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int sebze_biber_icon = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int sebze_domates_icon = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int sebze_havuc_icon = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int sebze_patlican_icon = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int sebze_salatalik_icon = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int tohum_gubre_icon = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int tohum_meyveFidani_icon = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int tohum_meyveTohumu_icon = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int tohum_sebzeFidani_icon = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int tohum_sebzeTohumu_icon = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int tumUrunler_icon = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int twitterIcon = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int urun_etBalik_icon = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int urun_icecek_icon = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int urun_kahvaltilik_icon = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int urun_kisiselBakim_icon = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int urun_meyve_icon = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int urun_sebze_icon = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int urun_sossirke_icon = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int urun_tohumCicek_icon = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int urun_yag_icon = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int youtubeIcon = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int yumurta = 2130837556;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
